<h1>{{ $details['nombreProfesor'] }} </h1>
<h1>{{ $details['escuela'] }} </h1>
<h1>{{ $details['estudiante'] }} </h1>
<h1>{{ $details['rut'] }} </h1>
<h1>{{ $details['matricula'] }} </h1>
<h1>{{ $details['curso'] }} </h1>
<h1>{{ $details['nota'] }} </h1>
<h1>{{ $details['meses'] }} </h1>
<h1>{{ $details['horas'] }} </h1>